### ISSUE TITLE
Add support for reverse IPv6 lookups

### ISSUE THREAD

**Issue by bertvv** [bertvv/ansible-role-bind#10]
Reverse IPv6 lookups seem to be a bit of a challenge to set up[[1](#note1)], so automation of this process could be valuable.

<a name="note1">[1]</a> http://www.zytrax.com/books/dns/ch3/#ipv6

**Comment by robrant** [comment]
It would also be cool to automatically disable ipv6 as i don't think it does that at the moment. This post talks about having to add a specific OPTIONS flag to `/etc/sysconfig/named`: https://serverfault.com/questions/639061/network-unreachable-error-in-my-server-logs

It links out to: http://crashmag.net/disable-ipv6-lookups-with-bind-on-rhel-or-centos

Sorry if this is already known (I couldn't see it being implemented) and thanks for the great role.

**Comment by bertvv** [comment]
For reference, this will be useful for implementing IPv6 support: https://github.com/ansible/ansible/issues/18738#issuecomment-264739492
