### ISSUE TITLE
Ansible galaxy role is not synced with master branch.

### ISSUE THREAD

**Issue by zx1986** [bertvv/ansible-role-bind#102]
Not sure if this is an issue.
But role from Ansible galaxy has no `auth_transfer.j2` template for bind_dns_keys.

**Comment by blofeldthefish** [comment]
Hi @zx1986 I do not have access to refresh the Ansible Galaxy packaged version of this role.

I will see what I can do to arrange this...

**Comment by bertvv** [comment]
I'm going to release a new version shortly (hopefully later today). Sorry for the inconvenience & thank you for your patience!
