### ISSUE TITLE
forward only Zone Possible?

### ISSUE THREAD

**Issue by gentoo9ball** [bertvv/ansible-role-bind#103]
Is it possible to do a forward only zone some how? I do not think the forward variable is accepted in this manner.

Thanks for a great playbook!

**Comment by ayprof** [comment]
I am also interested in this.

**Comment by blofeldthefish** [comment]
This should be fairly simple to achieve, by adding conditional checks in the "named.conf" templates, and also in the "master.yml" to prevent anything connected to reverse zones, based on a configuration variable.
