### ISSUE TITLE
dnssec-lookaside auto no longer supported on RHEL 7

### ISSUE THREAD

**Issue by dmc5179** [bertvv/ansible-role-bind#104]
This happens even when I set dnssec to off. The template j2 file contain the auto setting so bind fails right away.

TASK [bertvv.bind : Master | Main BIND config file (master)] ******************************************************************************************************************************************************
fatal: [ec2-X-X-X-X.compute-1.amazonaws.com]: FAILED! => {"changed": false, "checksum": "530edf2e5a097ed58d1e0371aa4fd49d80c78d6e", "exit_status": 1, "msg": "failed to validate", "stderr": "", "stderr_lines": [], "stdout": "/home/ec2-user/.ansible/tmp/ansible-tmp-1575861474.360141-87800793241846/source:22: dnssec-lookaside 'auto' is no longer supported\n/home/ec2-user/.ansible/tmp/ansible-tmp-1575861474.360141-87800793241846/source:14: undefined ACL 'a'\n", "stdout_lines": ["/home/ec2-user/.ansible/tmp/ansible-tmp-1575861474.360141-87800793241846/source:22: dnssec-lookaside 'auto' is no longer supported", "/home/ec2-user/.ansible/tmp/ansible-tmp-1575861474.360141-87800793241846/source:14: undefined ACL 'a'"]}

**Comment by oneacik** [comment]
https://github.com/bertvv/ansible-role-bind/pull/106

**Comment by dreyTee** [comment]
I removed unsupported option line and stuck on second error:
`undefined ACL 'a'`
Any clues?

**Comment by blofeldthefish** [comment]
Addressed with PR #106
