### ISSUE TITLE
How to create reverse zone only?

### ISSUE THREAD

**Issue by anuragbhatia** [bertvv/ansible-role-bind#109]
I am able to create a reverse zone by using networks and ipv6_networks but not sure how to create a reverse zone (without any forward zone)? 

I can create a reverse zone by putting appropriate ip6.arpa zone but no way to pass PTR records in that. Is that possible using this role?

**Comment by blofeldthefish** [comment]
As you can see, from the way this role is designed, excluding forward zone records is not currently an option.

Just having a quick skim through the templates for creating the named.conf file on the master and slaves, it seems that just having a new variable along the lines of "create forward zones ?" could be used to explicitly prevent the creation of the config for forward zones, as well as the actual creation of the forward zones...

Just for my own benefit, what would be a valid use-case for having a DNS server which only provides reverse zones for lookups ?

**Comment by bertvv** [comment]
Will be implemented in the next release. For each zone, you'll be able to specify whether to skip creating either the forward or the reverse zone. It's documented in the README.
