### ISSUE TITLE
Allow top host to be configured: add an A record for the domain

### ISSUE THREAD

**Issue by jdelaporte** [bertvv/ansible-role-bind#11]
In my domain, the top of the domain resolves to a webserver. I don't see a way to configure that with this role. In my zone file, the entry is just below the NS entries in the ORIGIN . section, and is unique because it only contains the domain name, not a hostname, like so:

csit.parkland.edu.      IN     A   216.x.x.x 

My current DNS server is ages out of date, and there may be a newer/better way to configure the top host now. Can this role set up a resolution for the domain?

**Comment by bertvv** [comment]
Will do! I have already have it working locally. I had to make an adjustment to te reverse zone template, but it already works in the forward zone by setting the name of the host to '@' (= the value of $ORIGIN, or your domain name):

```Yaml
bind_zone_hosts:
  - name: '@'
    ip: 192.0.2.20
    aliases:
      - www
```

I'll release a new version shortly.

**Comment by jdelaporte** [comment]
Fantastic! Thanks!
