### ISSUE TITLE
TASK "Master | Main BIND config file (master)" ~ AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by IoTPlay** [bertvv/ansible-role-bind#112]
Hi, trying to get this role working on a Raspberry Pi. - O/S Raspbian Stretch. Will it work?

Got it working up to TASK `[bertvv.bind : Master | Main BIND config file (master)]`.

Getting the error:`fatal: [rh02]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'match_list'"}`

Could you point me in a direction to resolve?

**Comment by blofeldthefish** [comment]
Whilst I can't guarantee that this role will work with Raspbian (it should, it's certified with Debian Stretch which Raspbian is based on...)

I would suggest you have misconfigured something around bind_acls, have a look in the README for an example.  If bind_acls is configured, then a dictionary called match_list should be present

Good luck!

**Comment by IoTPlay** [comment]
Thank you, will have a look. Will report back !

**Comment by IoTPlay** [comment]
All working, thank you !

**Comment by blofeldthefish** [comment]
No problem, glad it all worked out...
