### ISSUE TITLE
When testing role with molecule on host with other container running, verification will fail as master and slave have non consistent IPs

### ISSUE THREAD

**Issue by GR360RY** [bertvv/ansible-role-bind#131]
In the converge logic we assume ns1 has 172.17.0.2 ip and ns2 has 172.17.0.3 ip. This approach will fail if we have other docker container running on the local machine. This can be addressed by explicitly specifying IP configuration per container in `molecule.yml`. This will simplify testing and reduce requirements (from README.md). 

I can follow up with the PR

**Comment by bertvv** [comment]
True. I'd be grateful if you can take a look at this! I was aware that this could cause problems on systems with running Docker containers, but never got to fixing it...

**Comment by GR360RY** [comment]
@bertvv , the issue is address in https://github.com/bertvv/ansible-role-bind/pull/132
