### ISSUE TITLE
Support SRV records

### ISSUE THREAD

**Issue by jdelaporte** [bertvv/ansible-role-bind#16]
Hi Bert, 

I'd love to see SRV and TXT records be able to be added to the zone file to support Kerberos realm and RedHat IdM/FreeIPA authentication servers. 

For example: 
; ldap servers
_ldap._tcp              IN SRV 0 100 389        hostname

;kerberos realm
_kerberos               IN TXT                              KERBEROS.REALM.NAME

; kerberos servers
_kerberos._tcp          IN SRV 0 100 88         hostname
_kerberos._udp          IN SRV 0 100 88         hostname
_kerberos-master._tcp   IN SRV 0 100 88         hostname
_kerberos-master._udp   IN SRV 0 100 88         hostname
_kpasswd._tcp           IN SRV 0 100 464        hostname
_kpasswd._udp           IN SRV 0 100 464        hostname

;ntp server
_ntp._udp               IN SRV 0 100 123        hostname

; CNAME for IPA CA replicas (used for CRL, OCSP)
ipa-ca                  IN A                    ip.address

**Comment by bertvv** [comment]
That sounds easy to do, I'll get to it... ;-)

**Comment by bertvv** [comment]
Done, I released a new version (3.4.0) with support for SRV and TXT. I also included tests for this feature, based on your example.

Happy I could ship this a bit quicker than your previous feature request ;-)

**Comment by jdelaporte** [comment]
Wow, that's awesome! Thanks!

On Thu, May 26, 2016 at 4:21 AM, Bert Van Vreckem <notifications@github.com>
wrote:

> Done, I released a new version (3.4.0) with support for SRV and TXT. I
> also included tests for this feature, based on your example.
>
> Happy I could ship this a bit quicker than your previous feature request
> ;-)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bertvv/ansible-role-bind/issues/16#issuecomment-221820694>
>



-- 


Joanna Delaporte
Linux Systems Administrator | Parkland College
joannadelaporte@gmail.com
