### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jonesbusy** [bertvv/ansible-role-bind#161]
Hi,

I'm looking for this commit ce74398efda31ece22556c7720ca0835f18b68af (python switch) to be included on a release.

Is it plan to release a 5.1 soon ?

I would prefer to depend on a release on my galaxy file instead of master.

Thanks!

**Comment by bertvv** [comment]
Indeed, fair point! I'll be looking into this shortly.

**Comment by bertvv** [comment]
You had to wait for a long time, but v5.1.0 was just released! https://galaxy.ansible.com/bertvv/bind
