### ISSUE TITLE
main task not created log files from template, result - crash bind9 after start

### ISSUE THREAD

**Issue by Nerdsav** [bertvv/ansible-role-bind#163]
if set variables for template:
  bind_log
  bind_query_log
  bind_other_logs.file

sample template:
```bash
bind_log: '/var/log/named-misc.log'
bind_query_log:
  file: '/var/log/named-query.log'
  versions: 4
  size: 4m
bind_other_log:
  name: default
  file: '/var/log/named-misc.log'
  versions: 4
  size: 4m
```
when result play role:
```bash
RUNNING HANDLER [reload bind] ****************************************************************************************
fatal: [infra.b02]: FAILED! => {"changed": false, "msg": "Unable to reload service bind9: Job for bind9.service failed.\nSee \"systemctl status bind9.service\" and \"journalctl -xe\" for details.\n"}
```

**Need create folder for log paths and create with touch log-files:**

I`m adding to task/main.yml this code For Fix bug:
```bash
- name: Ensure runtime files in config exist
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ bind_owner }}"
    group: "{{ bind_group }}"
    mode: 0660
  become: yes
  with_items:
    - "{{ bind_log }}"
    - "{{ bind_query_log.file }}"
    - "{{ bind_other_logs.file }}"
  when: bind_log|length>0
    or (bind_query_log.file|length>0 or bind_other_logs.file|length>0)
  tags: bind
```

This is bug!

**Comment by bertvv** [comment]
Thanks! I implemented the requested change.

**Comment by bertvv** [comment]
I've been looking into this, but it's not as simple as you suggest with the code snippet (which doesn't work, I'm afraid).
The role expects that `bind_log` is a relative path w.r.t. `bind_dir`. You specify an absolute path, though, which confuses the code.
To implement this correctly in all circumstances, it would require a lot of code and a lot of conditionals.

I think it's easier to ensure that the desired log files exist before applying the role by creating them in your playbook in the `pre_tasks:` section.
