### ISSUE TITLE
Feature: single entry reverse zones (for AWS Elastic IPs)

### ISSUE THREAD

**Issue by jdelaporte** [bertvv/ansible-role-bind#17]
Hi Bert, 

When I use this role to create reverse zones for my Elastic IPs, I end up with the origin of the full IP address, and then a record for the full IP address. PTR resolution doesn't work unless I remove the IP address from the record. 

Maybe the reverse zone template can only insert the non-matching part of the reverse lookup address?

Thanks for an awesome role! I still use it all the time.
Joanna

**Comment by bertvv** [comment]
I don't quite understand, sorry. Can you give an example of expected and actual behaviour?

I'm really grateful for all your feedback, which has made the role to what it is now!

**Comment by jdelaporte** [comment]
I'm not very familiar with jinja, but it looks like you do a check to see if bind_zone_hosts list has more than 1 entry. I've been combining all my records for all zones into one set of vars and running my role once, rather than once for each bind_zone_network. It works great other than ending up with reverse zones that don't resolve PTRs for single entries. I end up with this:

$ORIGIN 217.174.29.52.in-addr.arpa.
--SOA record--
217.174.29.52 IN  PTR  files.sub.domain.edu.

PTR resolution works if I change it manually to:
$ORIGIN 217.174.29.52.in-addr.arpa.
--SOA record--
 IN  PTR  fileserver.sub.domain.edu.

**Comment by jdelaporte** [comment]
As far as I understand, the problem I experienced is because the name portion of the record (the left-hand field) is appended to the value of the ORIGIN.

**Comment by jdelaporte** [comment]
I think it's probably better to use @ instead of an empty space, actually. 

PTR resolution also works if I change it manually to:
$ORIGIN 217.174.29.52.in-addr.arpa.
--SOA record--
@ IN PTR fileserver.sub.domain.edu.

**Comment by jdelaporte** [comment]
Maybe there's a way to put each hostname in my vars as @, with a cname. I'll poke at that a bit....
It looks like to use @ for each elastic IP (EIP), I would need to define a new bind_zone_name using the fqdn for each EIP. So, that would mean storing separate sets of vars to create a subdomain and reverse zone for every EIP. Since I want those hosts registered in my normal forward zone, I think it would be better (and maybe easier) to make the reverse template more aware.

**Comment by jdelaporte** [comment]
If there is only one host in the network...(even if I defined more than one bind_zone_host item)...
Desired behaviour:

$ORIGIN 217.174.29.52.in-addr.arpa.
--SOA record--
@ IN PTR fileserver.sub.domain.edu.

Actual behaviour:
$ORIGIN 217.174.29.52.in-addr.arpa.
--SOA record--
217.174.29.52 IN PTR fileserver.sub.domain.edu.

**Comment by jdelaporte** [comment]
We should be able to put a line like this in there, I think, but I haven't gotten a working placement figured out yet. In the context of the template, {{item}} is a network from the bind_zone_networks list. 

{% if host.ip == {{item}} %}

**Comment by jdelaporte** [comment]
Ahh, I got a working template (tested with one normal /24 reverse zone and several /32 reverse zones)...not tested with anything else. Now I'll figure out how to make a pull request again.

**Comment by bertvv** [comment]
Thanks, Joanna! I merged the PR #18 and made some small changes:

- Introduced variable `bind_log` for the log file (default value remains data/named.run, you can override it in your host/group_vars)
- Renamed `also_notify` to `bind_zone_also_notify`, to be consistent with naming conventions (role variables start with role name)
- Added documentation for the new variables and change log, gave credit where due

If you have a suggestion for a test case that triggers the if-test you added in the template, that's always welcome. See `test.yml` in the tests branch.

Thank you for all your contributions, both by giving valuable feedback and now by improving the role.
