### ISSUE TITLE
Skipping master.yml

### ISSUE THREAD

**Issue by josetaas** [bertvv/ansible-role-bind#19]
Just faced an issue where the following condition was always failing:

`when: ansible_all_ipv4_addresses|last == bind_zone_master_server_ip`

My guest is set up so that it has two IP addresses, and the issue was that
`ansible_all_ipv4_addresses|last` was not referring to the one I set up to be the `bind_zone_master_server_ip`.

I'm not certain if there are any drawbacks, but what I did was replace the conditional with:

`when: bind_zone_master_server_ip not in ansible_all_ipv4_addresses`

**Comment by bertvv** [comment]
Good one, thanks! I'll adapt the code.

**Comment by bertvv** [comment]
I just published a new version on Ansible Galaxy with this change. Thanks!
