### ISSUE TITLE
Feature Request: Support Views/Split DNS Configuration

### ISSUE THREAD

**Issue by dx-zone** [bertvv/ansible-role-bind#213]
With multiple views we can define different DNS data (such as records and zones) for different groups of clients or for different scenarios. I'm not sure if this role support multiple views or Split DNS configuration, but if not, I'm requesting a feature to support multiple views (split DNS configuration), to provide different DNS responses to internal clients (within an organization's network) and external clients (outside the network). For example:

```
view "internal" {
    match-clients { 192.168.0.0/24; };
    zone "example.com" {
        type master;
        file "internal-zones/db.example.com.zone";
    };
};
```

```
view "external" {
    match-clients { any; };
    zone "example.com" {
        type master;
        file "external-zones/db.example.com.zone";
    };
};
```

**Comment by bertvv** [comment]
I'm sorry, but we are currently not able to implement feature requests.
