### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by inntran** [bertvv/ansible-role-bind#215]
Hi @bertvv,
It has been over a year since last update to this repo, do you time or any plan to review those open PRs?

Best wishes.

**Comment by bertvv** [comment]
Thank you for your interest in this role!

Unfortunately, it is not possible for me to plan for integrating the open PRs into the codebase. Ensuring the quality of the role has become quite challenging, as even seemingly simple PRs have introduced regressions in the past. Currently, I don't have enough free time to commit to this project. There's two other contributers with admin access to the repository, but it seems that they as well are currently not able to spend time on this. 

If there was a project like [Vox Pupuli](https://voxpupuli.org) in the Ansible community, I would probably submit the code there. Alternatively, if anyone would like to become involved in this project, or take over active development, I'm certainly open to discuss this.

**Comment by inntran** [comment]
OK, thanks for your hard work!
Maybe it's a good time to Archive this repo so people can contribute/fork elsewhere.
