### ISSUE TITLE
For slave servers, SELinux needs adjusting to allow zone files to be written

### ISSUE THREAD

**Issue by blofeldthefish** [bertvv/ansible-role-bind#24]
Zone transfers fail with: "dumping master file: tmp-xxxxxxxxxxxxx: open: permission denied" on slaves.

To resolve, on slave issue:
setsebool -P named_write_master_zones true

to resolve in this role, in tasks/slave.yml:
- name: Slave | permit master transfers
  seboolean: name=named_write_master_zones state=yes persistent=yes

but this adds a requirement on the "libsemanage-python" module ;-)

Should this be included in the role, or a pre-requisite outside of the role ?

**Comment by nishen** [comment]
in:
ansible-role-bind/templates/slave_etc_named.conf.j2

on lines 57 and 65, if you prefix the path with "slaves/" it writes to the slaves folder [/var/named/slaves] which has the correct permissions to allow writing the slave files.

57
- file "{{ bind_zone_name }}";
+ file "slaves/{{ bind_zone_name }}";

65
- file "{{ network|reverse_lookup_zone }}";
+ file "slaves/{{ network|reverse_lookup_zone }}";

**Comment by bertvv** [comment]
Should have been fixed by commit 2d6511d
