### ISSUE TITLE
Problem with CNAME only

### ISSUE THREAD

**Issue by nertwork** [bertvv/ansible-role-bind#26]
I'm not able to create records that are CNAME only with this playbook.

**Comment by bertvv** [comment]
This will be fixed as soon as I merged PR #21 (working on it!)

**Comment by bertvv** [comment]
As a matter of fact, the intended use of this role is for an authoritative-only name server. A `CNAME`-only record does not fit into this use case, as far as I know. I will add this functionality, but mixing the functionality of an authoritative and caching name server is [not considered to be best practice](http://www.zytrax.com/books/dns/ch4/).
