### ISSUE TITLE
Add support for allow-query-cache

### ISSUE THREAD

**Issue by asghaier** [bertvv/ansible-role-bind#43]
It is very useful to have caching features working for a bind server, this allows the system administrator to use much less bandwidth and queries.

**Comment by asghaier** [comment]
Not sure if this is actually exactly the same as allow-recursion, I will test with allow-recursion and see if the server uses the cache anyway to respond to the same query. If this turns out to be the case I will just close this issue.

**Comment by bertvv** [comment]
The primary use case for this role is as an authoritative-only server for a specific domain. Providing both functions, i.e. authoritative and caching, is not a good idea. See <http://www.zytrax.com/books/dns/ch4/index.html#cache> for background, that's basically my bible for anything BIND-related. I already enabled allow-recursion (set `bind_recursion` to true), but I do not recommend this. If recursion is enabled, BIND will automatically cache those queries.
