### ISSUE TITLE
Add support for simple forward zones

### ISSUE THREAD

**Issue by asghaier** [bertvv/ansible-role-bind#44]
This could be very useful if forwarding is required only for a specific zone/domain and a Master/Slave configuration would not be possible.
Combine this with allow-query-cache and the bind server will start to take care of most of the required queries minimizing bandwidth and requested to the forward zone.
This is also very useful if the forward zone is private and not known on the Internet.

**Comment by bertvv** [comment]
As I stated in a previous comment on a similar issue, this role is not meant for a forwarding DNS server, so I have no plans to implement this myself.
