### ISSUE TITLE
DNS slave config documentation

### ISSUE THREAD

**Issue by chicks-net** [bertvv/ansible-role-bind#54]
When I started using this playbook, even after reading the docs a few times, I was not sure that it would even work with a slave that didn't also do master for some zones.  I figured things out by looking at what was in the templates.  I thought others might appreciate an example in the docs so I started a [branch for that](https://github.com/fini-net/ansible-role-bind/tree/document-slave-config).

While doing that I noticed the table under ["Minimal variables..."](https://github.com/fini-net/ansible-role-bind/tree/document-slave-config#minimal-variables-for-a-working-zone) that lists what is required for master vs slave.  It says that `bind_zone_domains.name_servers` and `bind_zone_domains.networks` are required for a slave, but it didn't seem to be necessary for me.  Am I doing something wrong here or should I correct the docs for that too?

**Comment by cscashby** [comment]
This was really useful - hope this gets merged!  Have you sent a PR for the documentation?

**Comment by chicks-net** [comment]
Thanks!
