### ISSUE TITLE
why is "bind_zone_master_server_ip" required when we could only configure Master zone?

### ISSUE THREAD

**Issue by hellt** [bertvv/ansible-role-bind#59]
In a very simple lab scenario where we only need to configure a master zone, why would we need `bind_zone_master_server_ip` as a requirement?

Its only used in slave zones - https://github.com/bertvv/ansible-role-bind/search?q=bind_zone_master_server_ip&unscoped_q=bind_zone_master_server_ip

**Comment by bertvv** [comment]
The value is used on [line 97 and 100 of tasks/main.yml](https://github.com/bertvv/ansible-role-bind/blob/27b57a174e33053ac506bb2335f7297eb5db3a1c/tasks/main.yml#L97) to select whether the target machine should be set up as either a master or slave server. I haven't thought of an other way to do this.

The way it works now is: if one of the IP addresses of the machine matches `bind_zone_master_server_ip`, the `master.yml` playbook is run, and if not the `slave.yml` playbook.

I don't know why that line does not appear in the search result that you linked to...

**Comment by bertvv** [comment]
I hope you're ok with me closing this issue, as it is a question, not a request for improvement or bug report. If you feel your question wasnt't answered, feel free to reopen and/or continue the conversation!
