### ISSUE TITLE
Add TTL to individual resource records

### ISSUE THREAD

**Issue by WRJFontenot** [bertvv/ansible-role-bind#61]
bind_zone_domains:
  - name: mydomain.com
    hosts:
      - name: pub01
        ip: 192.0.2.1
        ipv6: 2001:db8::1
        ttl: 300
        aliases:
          - name: ns
            ttl: 300
    name_servers:
      - name: ns1
        ttl: 900
    delegate:
      - name: foo
        dns: 192.0.2.1
        ttl: 900
    mail_servers:
      - name: mail
        preference: 10
        ttl: 300

**Comment by bertvv** [comment]
This is doable, but will take some time...

**Comment by mikysal78** [comment]
I see https://github.com/bertvv/ansible-role-bind/pull/69 but TTL for records NS and MX?

**Comment by blofeldthefish** [comment]
Merged into master with the additional record types.
