### ISSUE TITLE
multi server

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#72]
if i have multi server, example 3 hardware server.
ns1.domain.tld (master)
ns2.domain.tld (slave)
ns3.domain.tld (slave)

my hosts is
[dns-server]
ns1.domain.tld ansible_user=root ansible_port=2400
ns2.domain.tld ansible_user=root ansible_port=2400
ns3.domain.tld ansible_user=root ansible_port=2400

how can I say that ns1 is master and ns2 and ns3 is slave?

**Comment by blofeldthefish** [comment]
As long as bind_zone_master_server_ip is set to the IP address of ns1.domain.tld

Then all three servers *should* be defined as respective master or slave servers...

**Comment by mikysal78** [comment]
thanks!
