### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#74]
your example is:
    networks:
      - '192.0.2'
      - '10'
      - '172.16'

if network is 172.16.18.0/29 ?
Thanks.

**Comment by blofeldthefish** [comment]
Not straightforward ;-)

https://tools.ietf.org/html/rfc2317  details the complexity (and which this role currently does not support...)

And halfway down:
https://randombio.com/linuxsetup59.html

Has another clunky workaround...

But again, to re-iterate this role does not currently support this....

**Comment by blofeldthefish** [comment]
You can't (easily) use with subnets smaller than /24, due to the complexities detailed in the prior links I provided.   Otherwise, for /24 or larger subnets, It should work with private or public subnets....

**Comment by mikysal78** [comment]
ok...thanks!
