### ISSUE TITLE
Default `mail_servers` is not working

### ISSUE THREAD

**Issue by mrmeszaros** [bertvv/ansible-role-bind#77]
According to the README, a the `mail_servers` zone variable defaults to `[{name: mail, preference: 10}]`.

However, in the `bind_zone.j2` template file it seems to default to `[]`.

Either the README or the template should be changed.

**Comment by mrmeszaros** [comment]
@bertvv This seems to be an easy one, so if You don't mind, I can create a PR with either of the solutions :-)

**Comment by blofeldthefish** [comment]
I would suggest an update to the README to align the two, with minimal impact to existing users.

If you decide on changing the default in the code, adding to default/main.yml is a more appropriate place, than in the template...

**Comment by mrmeszaros** [comment]
I will see if I can find a way of extending the defaults to reflect the README :slightly_smiling_face:

Otherwise I agree on rather changing the README - since maybe not all systems have a mail server, so the extra entry would pollute the zone file.

**Comment by bertvv** [comment]
I'm changing the README, as suggested. Thank you for catching this, @mrmeszaros!
