### ISSUE TITLE
Add support for zone transfers in named.conf.j2

### ISSUE THREAD

**Issue by jdelaporte** [bertvv/ansible-role-bind#8]
I don't see support for specifying zone transfers. I am considering how I might incorporate it for my environment, so I might submit a pull request if I get it figured out soon.

**Comment by bertvv** [comment]
Indeed, I haven't implemented that. What is it exactly that you need? Adding "allow-transfer" to the global options is easy, is that sufficient?

**Comment by jdelaporte** [comment]
In my existing bind config, I have access control lists (acl) specified with multiple IPs per ACL. So, can we use a dictionary style variable like the following? 
bind_zone_acls:
  - name: 'ISPPRI'
    ips:
    - 'ip1'
    - 'ip2'
  - name: 'ISPSEC'
    ips:
    - 'ip1'
  - name: 'CAMPUSLEGACY'
    ips:
    - 'ip1'
    - 'ip2'
    - 'ip3'
    - 'ip4'
  - name: 'CAMPUSNEW'
   - 'ip1'
   - 'ip2'

The role would turn these into entries as acls near the beginning of the config file. And then, in options for allow-transfer, the role would add each ACL name. I suppose someone will want more granularity to control which zones transfer where, but I don't need it right now. Alternatively, we could just write a list of IP addresses to allow-transfer, but I think the ACLs might be better practice.

**Comment by bertvv** [comment]
I wrote an implementation in branch feature/8. Can you take a look if that's what you expect? Feedback welcome!

To see how to use the feature: I updated the documentation and the test playbook with an example.

**Comment by bertvv** [comment]
I haven't heard from you, so I'm going to merge the feature branch. If you have additional feedback on the implementation, don't hesitate to let me know or to open another issue.

**Comment by jdelaporte** [comment]
Hi Bert,

I've been tangling with some other stuff that needed to be fixed. Today I
hope to get back to building my bind vars and playbook. At any rate, I'll
be taking a close look soon. Thanks!

Joanna

**Comment by bertvv** [comment]
Trust me, I know how it is... ;-)

I released a new version, v3.1.0 that includes this feature.
