### ISSUE TITLE
no space in allow-update

### ISSUE THREAD

**Issue by mikysal78** [bertvv/ansible-role-bind#80]
https://github.com/bertvv/ansible-role-bind/blob/1d36bf25b6e19ce67a5f05d5437ac024d69846cd/templates/master_etc_named.conf.j2#L86

if I have more network does not insert spaces in zone, example:
  allow-update { 10.27.253.0/24;10.27.22.1; };
correct syntax is:
  allow-update { 10.27.253.0/24; 10.27.22.1; };

**Comment by blofeldthefish** [comment]
This is fixed.  I have added the changes to my PR #75
