### ISSUE TITLE
Missing directory for slave zones on Ubuntu 18.04

### ISSUE THREAD

**Issue by petmit** [bertvv/ansible-role-bind#90]
Slave servers are configured to dump zone files to `slaves/{{ bind_zone.name }}`. Since this directory does not exist on Ubuntu 18.04, the bind daemon will log the following error:

`dumping master file: slaves/tmp-sSS2aSGJFT: open: file not found`

It seems there are two options for fixing this:

1. Add a task to create the `{{ bind_zone_dir }}/slaves` directory on slave servers.
2. Configure bind to dump zone files to `{{ bind_zone_dir }}` for slave servers.

I have currently only tested this on Ubuntu 18.04.

**Comment by seberm** [comment]
I had the same problem on Debian and my OSMC. My patch: #91 . It basically does the [1].

**Comment by blofeldthefish** [comment]
PR #91 has now been merged, addressing this issue.   Thanks to @seberm for the contribution.

**Comment by mikysal78** [comment]
task/slave.yml
---
- name: Ensure runtime directories referenced in config exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ bind_group }}"
    mode: 0770
  with_items:
    - "{{ bind_dir }}/dynamic"
    - "{{ bind_dir }}/data"
    **- "{{ bind_dir }}/slaves"**
    - "{{ bind_zone_dir }}"
  tags: bind
