### ISSUE TITLE
filter AAAA option 

### ISSUE THREAD

**Issue by vot4anto** [bertvv/ansible-role-bind#97]
Hi,
 is it possibile to add the follow as a variable of the role?
https://kb.isc.org/docs/aa-00576

Thanks

**Comment by blofeldthefish** [comment]
This is of course possible.

We look forward to any PRs to add this functionality in due course!

**Comment by bertvv** [comment]
At the moment, I have no time to implement and thoroughly test this feature, sorry!

PRs are welcome, though...
