### ISSUE TITLE
slaves dir for cache

### ISSUE THREAD

**Issue by vot4anto** [bertvv/ansible-role-bind#98]
I add the follow in slave.yml.
- name: Create Slaves dir to transfer zone
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ bind_group }}"
    mode: 0770
  with_items:
    - "{{ bind_dir_slave_caches }}"
  tags: bind

and in the main.yml:
bind_dir_slave_caches: '/var/cache/bind/slaves'

because I have on slave the follow erro in log
21-Oct-2019 15:14:15.322 dumping master file: slaves/tmp-JcE5VR0r8m: open: file not found

**Comment by kornrunner** [comment]
Seems sorted via #91

**Comment by blofeldthefish** [comment]
Hi @vot4anto can you confirm whether #91 has addressed this issue for you ?

**Comment by bertvv** [comment]
Should indeed be sorted with #91. A new version with this fix will be released on Galaxy shortly (hopefully later today).
